"""
ArcHillx — Multi-Agent Governance: Public Data Contracts
========================================================
Defines enums and dataclasses used throughout the MasterGovernor decision chain.
Standalone — no MGIS imports.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Dict, List, Optional


# ── Decision Enums ────────────────────────────────────────────────────────────

class AuditDecision(str, Enum):
    """MasterGovernor final ruling."""
    APPROVE  = "APPROVE"   # Approved — allow execution
    REJECT   = "REJECT"    # Rejected — plan must be revised
    VETO     = "VETO"      # Vetoed — triggers circuit-breaker freeze
    ABANDON  = "ABANDON"   # Abandoned — triggers task redesign


class AuditorRole(str, Enum):
    """Specialist auditor roles."""
    UI_AUDITOR          = "UI_AUDITOR"
    CODE_AUDITOR        = "CODE_AUDITOR"
    SECURITY_AUDITOR    = "SECURITY_AUDITOR"
    PERFORMANCE_AUDITOR = "PERFORMANCE_AUDITOR"


class SystemMode(str, Enum):
    """Global system degradation state."""
    NORMAL  = "NORMAL"   # Normal operation
    LIMITED = "LIMITED"  # Globally degraded (consecutive VETO limit exceeded)


# ── Data Classes ──────────────────────────────────────────────────────────────

@dataclass
class FeedbackPayload:
    """
    Structured feedback returned to the executing Agent on REJECT.
    The agent must revise the plan and must not repeat the same error_signature.
    """
    error_type:             str
    violated_rule:          str
    improvement_suggestion: str
    confidence_score:       float
    error_signature:        str   # SHA-256(error_type + violated_rule)[:16]

    def to_dict(self) -> Dict:
        return asdict(self)


@dataclass
class AuditEntry:
    """
    Immutable audit record written to ah_audit_log.
    """
    audit_id:           str
    task_id:            str
    executor_id:        str
    decision:           str   # AuditDecision.value
    auditor_role:       str   # highest-risk auditor role
    risk_score:         float
    feedback_json:      str   # JSON-serialised FeedbackPayload or "{}"
    solution_signature: str   # SHA-256(sorted executor output)[:24]
    created_at:         str


@dataclass
class RedesignTask:
    """
    Redesign instruction generated by AbandonEngine when ABANDON is triggered.
    Signatures in excluded_signatures must not appear in the new plan.
    """
    original_task_id:    str
    redesign_task_id:    str
    excluded_signatures: List[str]
    redesign_mode:       bool = True
    created_at:          str  = ""

    def to_dict(self) -> Dict:
        return {
            "original_task_id":    self.original_task_id,
            "redesign_task_id":    self.redesign_task_id,
            "excluded_signatures": self.excluded_signatures,
            "redesign_mode":       self.redesign_mode,
            "created_at":          self.created_at,
        }
